{"metadata":{"language_info":{"name":"python","version":"3.7.8","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"}},"nbformat_minor":5,"nbformat":4,"cells":[{"cell_type":"markdown","source":"# Ejercicio 1: Tracebaks","metadata":{},"id":"c7d7fa4d-9aa6-4fa9-ab61-31d6f71bd329"},{"cell_type":"markdown","source":"Intenta crear un archivo de Python y asígnale el nombre open.py, con el contenido siguiente:","metadata":{},"id":"43f14d83-c82a-4299-9298-1fcc907b9cee"},{"cell_type":"code","source":"def main():\n    open(\"/path/to/mars.jpg\")\n\nif __name__ == '__main__':\n    main()","metadata":{"trusted":true},"execution_count":1,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-9601f336b3a4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'__main__'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m     \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-1-9601f336b3a4>\u001b[0m in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"/path/to/mars.jpg\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'__main__'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '/path/to/mars.jpg'"],"ename":"FileNotFoundError","evalue":"[Errno 2] No such file or directory: '/path/to/mars.jpg'","output_type":"error"}],"id":"6861cefb-087d-4800-80ca-a9a3bc1dae67"},{"cell_type":"markdown","source":"## Controlando las excepciones","metadata":{},"id":"d5d00c17-b83c-4269-b46c-88726b07f9da"},{"cell_type":"markdown","source":"Sabemos que, si no existe un archivo o directorio, se genera FileNotFoundError. Si queremos controlar esa excepción, podemos hacerlo con un bloque try y except:","metadata":{},"id":"adfd3bae-19b9-4571-8c35-ad45a9f0aa7b"},{"cell_type":"code","source":"try:\n    open('config.txt')\n    except FileNotFoundError:\n        print(\"Couldn't find the config.txt file!\")\n","metadata":{"trusted":true},"execution_count":4,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-4-1f138793769b>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    except FileNotFoundError:\u001b[0m\n\u001b[0m         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-4-1f138793769b>, line 3)","output_type":"error"}],"id":"127e12b4-a48c-4433-8e41-eb62a58e6f0c"},{"cell_type":"markdown","source":"Aunque es común un archivo que no existe, no es el único error que podemos encontrar. Los permisos de archivo no válidos pueden impedir la lectura de un archivo, incluso si este existe. Vamos a crear un archivo de Python denominado config.py. El archivo tiene código que busca y lee el archivo de configuración del sistema de navegación:","metadata":{},"id":"45a98094-22c4-4d2e-8019-a05b6ffbc4a0"},{"cell_type":"code","source":"def main():\n    try:\n        configuration = open('config.txt')\n    except FileNotFoundError:\n        print(\"Couldn't find the config.txt file!\")\n\n\nif __name__ == '__main__':\n    main()","metadata":{"trusted":true},"execution_count":5,"outputs":[{"name":"stdout","text":"Couldn't find the config.txt file!\n","output_type":"stream"}],"id":"f89056e0-42d8-4b7c-81e2-c22227478cf7"},{"cell_type":"markdown","source":"A continuación, quita,ps el archivo config.txt y creamos un directorio denominado config.txt. Intentaremos llamar al archivo config.py para ver un error nuevo que debería ser similar al siguiente:","metadata":{},"id":"f4311c4e-b951-4590-a317-e5cc2f89e2a9"},{"cell_type":"code","source":"$ python config.py\nTraceback (most recent call last):\n  File \"/tmp/config.py\", line 9, in <module>\n    main()\n  File \"/tmp/config.py\", line 3, in main\n    configuration = open('config.txt')\nIsADirectoryError: [Errno 21] Is a directory: 'config.txt'","metadata":{"trusted":true},"execution_count":6,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-6-4ce17c9c4319>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    $ python config.py\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-6-4ce17c9c4319>, line 1)","output_type":"error"}],"id":"aea07234-14b5-4d3e-9fe7-e2ad44722027"},{"cell_type":"markdown","source":"Una manera poco útil de controlar este error sería detectar todas las excepciones posibles para evitar un traceback. Para comprender por qué detectar todas las excepciones es problemático, probaremos actualizando la función main():","metadata":{},"id":"b479114f-d6c9-44ae-8aa5-b1f1abdbe0d2"},{"cell_type":"code","source":"def main():\n    try:\n        configuration = open('config.txt')\n    except Exception:\n        print(\"Couldn't find the config.txt file!\")","metadata":{"trusted":true},"execution_count":8,"outputs":[],"id":"7486323c-f392-4fd8-b691-f88a8f4a989a"},{"cell_type":"markdown","source":"Ahora volvemos a ejecutar el código en el mismo lugar donde existe el archivo config.txt con permisos incorrectos:","metadata":{},"id":"c80c54f7-3231-469c-8e12-eb78d06d5865"},{"cell_type":"code","source":"$ python config.py","metadata":{"trusted":true},"execution_count":10,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-10-bf07be73c6e5>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    $ python config.py\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-10-bf07be73c6e5>, line 1)","output_type":"error"}],"id":"c6de26ce-d733-4751-9097-796e98a2ec16"},{"cell_type":"markdown","source":"Vamos a corregir este fragmento de código para abordar todas estas frustraciones. Revertiremos la detección de FileNotFoundError y luego agregamos otro bloque except para detectar PermissionError:","metadata":{},"id":"558b8418-2340-45a8-80e7-fd936f7648ee"},{"cell_type":"code","source":"def main():\n    try:\n        configuration = open('config.txt')\n    except FileNotFoundError:\n        print(\"Couldn't find the config.txt file!\")\n    except IsADirectoryError:\n        print(\"Found config.txt but it is a directory, couldn't read it\")","metadata":{"trusted":true},"execution_count":12,"outputs":[],"id":"ebda4b3a-7103-4586-825e-cd6191da0fa7"},{"cell_type":"markdown","source":"Ahora volvemos a ejecutarlo, en el mismo lugar donde config.txt está con el problema de permisos:","metadata":{},"id":"7c8b90cf-2074-436a-97fe-d2d981af4f50"},{"cell_type":"code","source":"$ python config.py","metadata":{"trusted":true},"execution_count":36,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-36-bf07be73c6e5>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    $ python config.py\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-36-bf07be73c6e5>, line 1)","output_type":"error"}],"id":"7b0b5ff4-ea5c-4590-9e83-e1e65b719974"},{"cell_type":"markdown","source":"Eliminamos el archivo config.txt para asegurarnos de que se alcanza el primer bloque except en su lugar:","metadata":{},"id":"4495a666-2a58-414b-a7f8-3d6589d4382e"},{"cell_type":"code","source":"$ rm -f config.txt\n$ python config.py","metadata":{"trusted":true},"execution_count":37,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-37-8d7f9bb88403>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    $ rm -f config.txt\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-37-8d7f9bb88403>, line 1)","output_type":"error"}],"id":"18e9447c-9760-4aa1-81ab-6f41afade428"},{"cell_type":"markdown","source":"Cuando los errores son de una naturaleza similar y no es necesario controlarlos individualmente, puedes agrupar las excepciones como una usando paréntesis en la línea except. Por ejemplo, si el sistema de navegación está bajo cargas pesadas y el sistema de archivos está demasiado ocupado, tiene sentido detectar BlockingIOError y TimeOutError juntos:","metadata":{},"id":"979ef85b-8331-45c6-b2ee-00de65cf665c"},{"cell_type":"code","source":"def main():\n    try:\n        configuration = open('config.txt')\n    except FileNotFoundError:\n        print(\"Couldn't find the config.txt file!\")\n    except IsADirectoryError:\n        print(\"Found config.txt but it is a directory, couldn't read it\")\n    except (BlockingIOError, TimeoutError):\n        print(\"Filesystem under heavy load, can't complete reading configuration file\")","metadata":{"trusted":true},"execution_count":38,"outputs":[],"id":"19aab4bf-8697-409c-92f8-ffa9459f7006"},{"cell_type":"markdown","source":"### Sugerencia","metadata":{},"id":"5218da50-ad6a-4db6-900d-574ca975df54"},{"cell_type":"markdown","source":"Control individual: Si necesitas acceder al error asociado a la excepción, debes actualizar la línea except para incluir la palabra clave as. Esta técnica es práctica si una excepción es demasiado genérica y el mensaje de error puede ser útil:","metadata":{},"id":"fe8d6d2d-c4ea-4511-b3d5-7d24e81f9510"},{"cell_type":"code","source":"try:\n        open(\"mars.jpg\")\n        except FileNotFoundError as err:\n            print(\"got a problem trying to read the file:\", err)","metadata":{"trusted":true},"execution_count":39,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-39-b9a89f109191>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    except FileNotFoundError as err:\u001b[0m\n\u001b[0m         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-39-b9a89f109191>, line 3)","output_type":"error"}],"id":"259d5e97-34b8-4bbb-b3e0-2159cd43246e"},{"cell_type":"markdown","source":"En este caso, as err significa que err se convierte en una variable con el objeto de excepción como valor. Después, usa este valor para imprimir el mensaje de error asociado a la excepción. Otra razón para usar esta técnica es acceder directamente a los atributos del error. Por ejemplo, si detecta una excepción OSError más genérica, que es la excepción primaria de FilenotFoundError y PermissionError, podemos diferenciarlas mediante el atributo .errno:","metadata":{},"id":"edfcbd94-df6e-4c32-a589-6c400dd2a49f"},{"cell_type":"code","source":"try:\n    open(\"config.txt\")\n    except OSError as err:\n        if err.errno == 2:\n            print(\"Couldn't find the config.txt file!\")\n    elif err.errno == 13:\n        print(\"Found config.txt but couldn't read it\")","metadata":{"trusted":true},"execution_count":40,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-40-e27297c8271a>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    except OSError as err:\u001b[0m\n\u001b[0m         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"],"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-40-e27297c8271a>, line 3)","output_type":"error"}],"id":"544138e2-df6a-48dd-b7d1-b2885f12df61"},{"cell_type":"markdown","source":"# Ejercicio 2: Generación de excepciones","metadata":{},"id":"7630fab6-72e9-4023-b70f-cdf0bb15b3cf"},{"cell_type":"markdown","source":"La generación de excepciones también puede ayudar en la toma de decisiones para otro código. Como hemos visto antes, en función del error, el código puede tomar decisiones inteligentes para resolver, solucionar o ignorar un problema.\n\nLos astronautas limitan su uso de agua a unos 11 litros al día. Vamos a crear una función que, con base al número de astronautas, pueda calcular la cantidad de agua quedará después de un día o más:","metadata":{},"id":"208604ef-7e17-467c-a914-8d93155f9a8e"},{"cell_type":"code","source":"def water_left(astronauts, water_left, days_left):\n    daily_usage = astronauts * 11\n    total_usage = daily_usage * days_left\n    total_water_left = water_left - total_usage\n    return f\"Total water left after {days_left} days is: {total_water_left} liters\"","metadata":{"trusted":true},"execution_count":41,"outputs":[],"id":"07cc5634-573d-49c4-872e-7034d4cb1246"},{"cell_type":"markdown","source":"Probemos con cinco astronautas, 100 litros de agua sobrante y dos días","metadata":{},"id":"e9441db3-feef-4f44-b302-0e04b87dcb63"},{"cell_type":"code","source":"water_left(5, 100, 2)\n'Total water left after 2 days is: -10 liters'","metadata":{"trusted":true},"execution_count":42,"outputs":[{"execution_count":42,"output_type":"execute_result","data":{"text/plain":"'Total water left after 2 days is: -10 liters'"},"metadata":{}}],"id":"8789fe0a-a350-4f10-9b6c-590b997848a6"},{"cell_type":"markdown","source":"Esto no es muy útil, ya que una carencia en los litros sería un error. Después, el sistema de navegación podría alertar a los astronautas que no habrá suficiente agua para todos en dos días. Si eres un ingeniero(a) que programa el sistema de navegación, podrías generar una excepción en la función water_left() para alertar de la condición de error:","metadata":{},"id":"4bfd7eaf-b4f7-49c0-99a4-45e15fbe6447"},{"cell_type":"code","source":"def water_left(astronauts, water_left, days_left):\n    daily_usage = astronauts * 11\n    total_usage = daily_usage * days_left\n    total_water_left = water_left - total_usage\n    if total_water_left < 0:\n        raise RuntimeError(f\"There is not enough water for {astronauts} astronauts after {days_left} days!\")\n    return f\"Total water left after {days_left} days is: {total_water_left} liters\"","metadata":{"trusted":true},"execution_count":25,"outputs":[],"id":"2ba56145-27e3-486c-aaec-a121a8dd7675"},{"cell_type":"markdown","source":"Ahora volvemos a ejecutarlo","metadata":{},"id":"641c889a-c626-4d0c-8d2d-9c3b63da2d70"},{"cell_type":"code","source":"water_left(5, 100, 2)","metadata":{"trusted":true},"execution_count":31,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-31-cb536572b4c6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mwater_left\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m100\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-25-23ad9d658ff7>\u001b[0m in \u001b[0;36mwater_left\u001b[0;34m(astronauts, water_left, days_left)\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mtotal_water_left\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwater_left\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mtotal_usage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mtotal_water_left\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"There is not enough water for {astronauts} astronauts after {days_left} days!\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0;34mf\"Total water left after {days_left} days is: {total_water_left} liters\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRuntimeError\u001b[0m: There is not enough water for 5 astronauts after 2 days!"],"ename":"RuntimeError","evalue":"There is not enough water for 5 astronauts after 2 days!","output_type":"error"}],"id":"6967f13c-16f0-4f30-9866-9b12475152cc"},{"cell_type":"markdown","source":"En el sistema de navegación, el código para señalar la alerta ahora puede usar RuntimeError para generar la alerta:","metadata":{},"id":"44056bbe-485c-4e4b-8830-75e28e619cf3"},{"cell_type":"code","source":"try:\n    water_left(5, 100, 2)","metadata":{"trusted":true},"execution_count":32,"outputs":[{"traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-32-f09207623b6f>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    water_left(5, 100, 2)\u001b[0m\n\u001b[0m                         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m unexpected EOF while parsing\n"],"ename":"SyntaxError","evalue":"unexpected EOF while parsing (<ipython-input-32-f09207623b6f>, line 2)","output_type":"error"}],"id":"8b59bbca-0f89-4c79-8807-14850c3c4953"},{"cell_type":"markdown","source":"La función water_left() también se puede actualizar para evitar el paso de tipos no admitidos. Intentenis pasar argumentos que no sean enteros para comprobar la salida de error:","metadata":{},"id":"62675224-1032-4fae-a125-ef101ef8ddc6"},{"cell_type":"code","source":"water_left(\"3\", \"200\", None)","metadata":{"trusted":true},"execution_count":33,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-33-440ddff11c7b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mwater_left\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"3\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"200\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-25-23ad9d658ff7>\u001b[0m in \u001b[0;36mwater_left\u001b[0;34m(astronauts, water_left, days_left)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mwater_left\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mastronauts\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwater_left\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdays_left\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0mdaily_usage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mastronauts\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0;36m11\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m     \u001b[0mtotal_usage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdaily_usage\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mdays_left\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m     \u001b[0mtotal_water_left\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwater_left\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mtotal_usage\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mtotal_water_left\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: can't multiply sequence by non-int of type 'NoneType'"],"ename":"TypeError","evalue":"can't multiply sequence by non-int of type 'NoneType'","output_type":"error"}],"id":"49b64283-308e-4db1-9d88-8f7c68262f70"},{"cell_type":"markdown","source":"El error de TypeError no es muy descriptivo en el contexto de lo que espera la función. Actualizaremos la función para que use TypeError, pero con un mensaje mejor:","metadata":{},"id":"adb3238e-13f3-4a3f-af61-8202c878d403"},{"cell_type":"code","source":"def water_left(astronauts, water_left, days_left):\n    for argument in [astronauts, water_left, days_left]:\n        try:\n            # If argument is an int, the following operation will work\n            argument / 10\n        except TypeError:\n            # TypError will be raised only if it isn't the right type \n            # Raise the same exception but with a better error message\n            raise TypeError(f\"All arguments must be of type int, but received: '{argument}'\")\n    daily_usage = astronauts * 11\n    total_usage = daily_usage * days_left\n    total_water_left = water_left - total_usage\n    if total_water_left < 0:\n        raise RuntimeError(f\"There is not enough water for {astronauts} astronauts after {days_left} days!\")\n    return f\"Total water left after {days_left} days is: {total_water_left} liters\"","metadata":{"trusted":true},"execution_count":34,"outputs":[],"id":"76e482fa-32c7-4490-9e12-0c249c2f412f"},{"cell_type":"markdown","source":"Ahora volvemos a intentarlo para obtener un error mejor:","metadata":{},"id":"e1fa22d3-e21f-4a47-bc3f-a94cfb34c985"},{"cell_type":"code","source":"water_left(\"3\", \"200\", None)","metadata":{"trusted":true},"execution_count":35,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-34-c9067c6af39d>\u001b[0m in \u001b[0;36mwater_left\u001b[0;34m(astronauts, water_left, days_left)\u001b[0m\n\u001b[1;32m      4\u001b[0m             \u001b[0;31m# If argument is an int, the following operation will work\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m             \u001b[0margument\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m10\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for /: 'str' and 'int'","\nDuring handling of the above exception, another exception occurred:\n","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-35-440ddff11c7b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mwater_left\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"3\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"200\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-34-c9067c6af39d>\u001b[0m in \u001b[0;36mwater_left\u001b[0;34m(astronauts, water_left, days_left)\u001b[0m\n\u001b[1;32m      7\u001b[0m             \u001b[0;31m# TypError will be raised only if it isn't the right type\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m             \u001b[0;31m# Raise the same exception but with a better error message\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 9\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"All arguments must be of type int, but received: '{argument}'\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     10\u001b[0m     \u001b[0mdaily_usage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mastronauts\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0;36m11\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m     \u001b[0mtotal_usage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdaily_usage\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mdays_left\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: All arguments must be of type int, but received: '3'"],"ename":"TypeError","evalue":"All arguments must be of type int, but received: '3'","output_type":"error"}],"id":"14176387-5149-40fe-b7f7-53cc31740186"},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[],"id":"6cc427c3-4b5d-443b-b478-2e951999e4fd"}]}